---
:user: username
:pwd: password
:tribe: gauleses
:execute_in_background: true
:url_base: http://ts5.travian.pt
:home: http://ts5.travian.pt/dorf1.php
:logout: http://ts5.travian.pt/logout.php
:url_farming: http://ts5.travian.pt/build.php?tt=2&id=39
:url_hero_adventure: http://ts5.travian.pt/hero_adventure.php
:save_troops: false
:farm_save_troops: farm_save
:hero_adventure_active: true
:farming: true
:limit_trop_to_farm: '10'
:off: '-1'
:build_url: http://ts5.travian.pt/build.php?id=
:clay_field: true
:cereal_field: true
:iron_field: true
:wood_field: true
